(in-package :lc3)

(defun build-vm (pathname)
  (dot "orig x3000")
  (jsr 'setup)
  (jsr 'interpret)
  (load "bits")
  (load "microcode")
  (load "instructions")
  (load "interpreter")
  (load "virtual-memory")
  (load "image")
  (read-image pathname)
  (dot "end"))
